version: "3.9"

services:
  database_rentx: #Nome do service para conexão entre app e db
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgress
    networks: 
      - mynet
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229 #Porta para utilizar o Debug
    volumes:
      - .:/usr/app
    networks: 
      - mynet
    links:
      - database_rentx
    depends_on:
      - database_rentx


volumes:
  pgdata:
    driver: local

networks: 
  mynet:
    name: my-shared-db-network
